src/lib/measure-webpage/index.ts
Summary:
Use transfer size instead of resource size. This is the correct number to computed the page weight that is needed for co2js (number of transferred bytes).
The value isn't stored in puppeteer's response object. Thus, a workaround with chrome dev protocol was used.
Context:
Closes #5
=> chore(lib): use transfer size instead of resource size

src/lib/measure-webpage/index.ts
Remove config parameter from signature and read it inside of method body.
=> chore(measure-webpage): simplify interface of measurePage method

.npmignore, NOTICE, README.md, example-manifests/measure-webpage.yml, package-lock.json, package.json, src/lib/green-hosting/README.md, src/lib/shell-exec-command/README.md, src/lib/timer/README.md, src/lib/webpage-impact/README.md
Polishing dependencies (npm audit fix), fixing package name and adapt manifest files, READMEs etc.
=> Prepare for publishing on npm

package-lock.json, package.json, src/__tests__/unit/lib/green-hosting/index.test.ts, src/lib/green-hosting/README.md, src/lib/green-hosting/index.ts
=> chore: refactor green hosting plugin to comply with IF 0.7.1 interface

src/lib/co2js/index.ts, src/lib/green-hosting/index.ts, src/lib/shell-exec-command/README.md, src/lib/shell-exec-command/index.ts, src/lib/timer/start.ts, src/lib/webpage-impact/index.ts, src/util/errors.ts, src/util/helpers.ts
=> chore(shell-exec-command): refactor shell exec plugin for new IF interface

src/__tests__/unit/lib/green-hosting/index.test.ts, src/lib/green-hosting/README.md, src/lib/green-hosting/index.ts, src/util/helpers.ts
=> chore(green-hosting): Add unit test for timestamp and duration adding if both are missing

src/__tests__/unit/lib/timer/start.test.ts, src/__tests__/unit/lib/timer/stop.test.ts, src/lib/timer/README.md, src/lib/timer/start.ts, src/lib/timer/stop.ts
=> chore(timer): refactor timer plugins for if 0.7.1

NOTICE, example-manifests/co2js.yaml, package-lock.json, package.json, src/__tests__/unit/lib/co2js/index.test.ts, src/config/strings.ts, src/lib/co2js/README.md, src/lib/co2js/index.ts, src/util/validations.ts
update co2js version
enable v3 and v4 version of SWD model
add tests (copied from if-unofficial-plugins, modified and added a test)
copied and updated README as well
=> chore(co2js): refactor co2js plugin for IF 0.7.1

README.md, example-manifests/measure-webpage.yml, src/__tests__/unit/lib/webpage-impact/index.test.ts, src/lib/webpage-impact/README.md, src/lib/webpage-impact/index.ts
=> chore(webpage-impact): refactor for IF 0.7.1

README.md, src/lib/co2js/README.md, src/lib/green-hosting/README.md, src/lib/shell-exec-command/README.md, src/lib/timer/README.md, src/lib/webpage-impact/README.md
=> chore: add notes to READMEs about IF version which has been tested

CONTRIBUTING.md, DCO
=> chore(other): add contribution guidelines and DCO

package-lock.json, package.json
now entirely unused and can be removed
=> chore(webpage-impacts): remove lighthouse dependency

.github/workflows/lint.yml
=> fix(ci): rename step from unit tests to lint

package-lock.json
npm audit reports a high vulnerability
ran npm aufit fix
=> chore(deps): update cross-spawn to 7.0.6

package-lock.json, package.json
=> update co2js to 0.16.4

LICENSE, package.json
see title
plus minor change in project title in package.json
=> restore original Apache 2.0 license

.github/workflows/create-version-bump-PR.yaml, scripts/bump_version.sh, scripts/publish_release.sh
Add script for version bumping and a github workflow to trigger it. Also add a script for building and publishing a release. It will triggered from the release repo.
=> feature: add release scripts and GH workflow for version bump

scripts/bump_version.sh
and make description of the script more precise
=> chore: use npm command for version bump

.npmrc, scripts/publish_release.sh
and use npm command to get the version
=> chore: fix usage of npm token

.github/workflows/create-version-bump-PR.yaml
the script was called with old, now wrong, cli args
=> fix: fix version bump workflow

scripts/bump_version.sh, scripts/publish_release.sh
move newline printing into subsequent echo command improve comment
=> fix: some small improvements on scripts

package-lock.json, package.json
To be able to create a version bump commit to 1.0.0 and subsequent release.
=> chore: set version to 0.0.0 for testing release process

scripts/publish_release.sh
testing finished, I hope
Signed-off-by: Alexander zur Bonsen <alexander.zur.bonsen@tngtech.com>
=> chore: uncomment publishing release step

scripts/bump_version.sh, scripts/publish_release.sh
Signed-off-by: Alexander zur Bonsen <alexander.zur.bonsen@tngtech.com>
=> chore: start release tags with v, e.g. v1.0.0 instead of 1.0.0

package-lock.json, package.json
I somehow butchered the renovate PR. Manually updating.
=> deps: update co2js to 0.16.5

src/__tests__/unit/lib/green-hosting/index.test.ts
=> chore: fix a wrong url in green hosting test
